name: Rapid Scan
on:
  workflow_dispatch:
    inputs:
       website:
       
jobs:
  rapidscan:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
      - run: python3 -m pip install .
      - run: python3 rapidscan.py "${{ github.event.inputs.website}}"
 
